list/urls.py
from django.urls import path
from . import views
app_name = "list"

urlpatterns = [
    path("", views.index, name="index"),
    path("clear", views.clear, name="clear"),
    path('save-tasks/', views.save_tasks, name='save_tasks'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("list.urls")),
]

list/models.py
from django.db import models

# Create your models here.

list/forms.py
from django import forms

class NewTaskForm(forms.Form):
    task = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'enter your todo'}))

list/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import NewTaskForm
from .Task import Task
from django.http import JsonResponse
import json

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"]=[]
        
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = Task(form.cleaned_data["task"])
            request.session["tasks"] += [task.__dict__]  # تبدیل آبجکت‌ها به دیکشنری
            return HttpResponseRedirect(reverse("list:index"))
        else:
            return render(request, "list/index.html", {"form":form,"tasks":request.session["tasks"]})
    else:
        form = NewTaskForm()
    return render(request, "list/index.html", {"form":form,"tasks":request.session["tasks"]})

def clear(request):
    request.session["tasks"] = []
    return HttpResponseRedirect(reverse("list:index"))


def save_tasks(request):
    if request.method == "POST":
        changeItems = json.loads(request.body)  # دریافت داده‌های JSON
        taskName = changeItems["task"]
        status = changeItems["task_status"]
        # اینجا می‌توان داده‌ها را در دیتابیس ذخیره کرد
        print("Received Finished Tasks:", changeItems) 
        for dict in request.session["tasks"]:
            if dict["taskname"] == taskName:
                if status == "open":
                    dict["status"] = "open"
                else:
                    dict["status"] = "finished"
        request.session.modified = True

        return JsonResponse({"status": "success", "message": "Tasks updated successfully!"})

    return JsonResponse({"status": "error", "message": "Invalid request!"}, status=400)

list/templates/list/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'list/style.css' %}">
    
    <title>Metodo</title>
</head>
<body>
  <div class="container text-center">
    <div class="row">
      <div class="col">
      </div>
      <div class="col-8">
        <!-- up navbar -->
        <div class="up-navbar">
          <ul>
            <li><a href="{% url 'list:index' %}">Metodo</a></li>
            <li style="float:right"><a href="{% url 'list:clear'  %}">Clear</a></li>
          </ul>  
        </div>
        <hr>
        {% if tasks %}
          <div class="body-content-container" style="display: block;">
        {% else %}
          <div class="body-content-container">
        {% endif %}
            <div class="form">
              <h2>Beat your Tasks</h2>
              <form action="{% url 'list:index' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                {% if tasks %}
                  <input type="submit">
                {% else %}
                  <input id="submit-first-task" type="submit" value="let's do it">
                {% endif %}
              </form>
            </div>
            {% if tasks %}
            <div class="tasks">
              <div class="row justify-content-around">
                  <div class="col-4">
                    <div id="task-column">
                      <h2>Open</h2>
                      <ul id="openTasks">
                        {% for task in tasks %}
                          {% if task.status == "open" %}
                            <li><input type="checkbox" onclick="changeStatus(this)" >{{task.taskname}}</li>
                          {% endif %}
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                  <div class="col-4">
                    <div id="task-column">
                      <h2>Finished</h2>
                      <ul id="finishedTasks">
                        {% for task in tasks %}
                          {% if task.status == "finished" %}
                            <li><input type="checkbox" onclick="changeStatus(this)"  checked>{{task.taskname}}</li>
                          {% endif %}
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
              </div>
            </div>  
            {% endif %}
        </div>    
      </div>
      <div class="col">
      </div>
    </div>
  </div>

  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> -->
  <script>
    function changeStatus(checkbox){
          let taskItem = checkbox.parentElement; // دریافت عنصر <li>
          let taskText = taskItem.textContent.trim(); // دریافت متن تسک (بدون چک‌باکس)
          let status = ""

          if (checkbox.checked) {
            document.getElementById("finishedTasks").appendChild(taskItem); // انتقال به لیست "Finished"
            taskItem.style.textDecoration = "line-through";
            taskItem.style.color = "gray";
            status = "finished";
            saveTasks(taskText, status);
          } else {
            document.getElementById("openTasks").appendChild(taskItem); // انتقال به لیست "Finished"
            taskItem.style.textDecoration = "";
            taskItem.style.color = "black";
            status = "open";
            saveTasks(taskText, status);
          }
    }

    function saveTasks(task, task_status) {
    fetch('/save-tasks/', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': getCSRFToken(), // برای محافظت CSRF
        },
        body: JSON.stringify({ task: task, task_status:task_status }) // ارسال آرایه به سرور
      })
      .then(response => response.json())
      .then(data => console.log("Server Response:", data))
      .catch(error => console.error("Error:", error));
    }

    // تابع برای دریافت مقدار CSRF (برای محافظت در برابر حملات CSRF)
    function getCSRFToken() {
        return document.querySelector('[name=csrfmiddlewaretoken]').value;
    }
  </script>
</body>
</html>